# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Segmentify-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic

pod "Segmentify" , '~> 1.1.0'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
  # Pods for Segmentify-Demo
  target 'NotificationService' do
      inherit! :search_paths
  end

end
