# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Segmentify-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic

pod "Segmentify"
# Use following POD for local development
  #pod 'Segmentify', :path => '/Users/ihalilaltun/Development/SEGMENTIFY_GIT/segmentify-ios-sdk'
pod 'Firebase/Messaging'
  # Pods for Segmentify-Demo
  target 'NotificationService' do
      inherit! :search_paths
  end
end
